"""empty message

Revision ID: 3faf181e8c55
Revises: 30fb1b056366
Create Date: 2021-02-27 18:14:08.909712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3faf181e8c55'
down_revision = '30fb1b056366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('lastname', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=80), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('user', 'username')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
